In [2]:
print(list(range(3))[3])

IndexError: list index out of range

In [4]:
text = 'hello'

print(text[4:100])

o


In [7]:
file = open("out.txt", "w")

for i in range(5):

    file.write(str(i))

file.close()

file = open("out.txt", "w")

for i in range(5, 10):

    file.write(str(i))

file.close()

file = open("out.txt", "r")

for i in file:
    print(i)


56789


In [41]:
def almost_double_factorial(n):
    result = 1
    for i in range(1, n + 1):
        if i % 2 != 0:
            result = result * i
    return result 

print(almost_double_factorial(0))

1


In [59]:
items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]

sorted_items = sorted(items, key=lambda x: x[1][-1])

sorted_items

[('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')]

In [172]:
x = [1, 2, 3, 4, 5]
x[slice(None, None, -2)] = [-1, -3, -5]

print(x)

[-5, 2, -3, 4, -1]


In [169]:
x = [1, 2, 3, 4, 5]
x[::-2] = [-1, -3, -5]

print(x)

[-5, 2, -3, 4, -1]


In [ ]:
def cumsum_and_erase(A, erase = 1):

    B = #YOUR CODE
    return B

In [2]:
sentences = ['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100']

def process(sentences):
    sentences = str.join()

    
    return result

In [3]:
204843-4703-(42666345 - 30962185)/2210


194844.0

In [4]:
(46056 + 1575936/3456)/456 + 207936/456

558.0

In [13]:
def process(sentences):
    result=[]
    for sentence in sentences:
        st=""
        for word in sentence.split():
            if word.isalpha():
                st+=word+ " "
            s1=st[0:-1]  
        result.append(s1)     
    return result

a = ['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100']

process(a)

['thousand devils', 'My name is', 'Room costs']

In [52]:
class Neuron:

    def __init__(self, w, f = lambda x: x):
        self.w = w
        self.f = f 
        self.x = [] 
    def forward(self, x):
        x = self.x
        w = self.w
        i = 0
        proiz = []
        while i < len(x):
            proiz = w[i] * x[i] 
        return proiz
    def backlog(self):
        return self.x
    

neuron = Neuron([0.1, 0.3, 0.2, 0.35, 0.7]) #Передача весов
print('neuron.forward = ' + str(neuron.forward([4, 1, 15, 16, 100]))) #Передача иксов
neuron.backlog()
type(neuron.backlog()) 

neuron.forward = []


list

In [56]:
class Neuron:

    def __init__(self, w, f = lambda x: x):
        self.w = w
        self.f = f
    def forward(self, x):
        a = self.w
        x = self.f
        i = 0
        mult = []
        while i<len(w):
            mult.append(w[i]*x[i])
            i+=1   
        return mult
    def backlog(self):
        self.x = x
        return x

In [57]:
def Test():
    test_neuron = Neuron([2, 3, 4, 5, 6], lambda x: x*x)
    if (test_neuron.forward([1, 2, 3, 4, 5]) == 4900 and test_neuron.backlog() == [1, 2, 3, 4, 5]):
        print("Задание успешно выполнено!")
    else:
        print("Ошибка в решении!")
    
Test()

NameError: name 'w' is not defined

In [66]:
class Neuron:

    def __init__(self, w, f = lambda x: x):
        self.w = w
        self.f = f
    def forward(self, x):
        self.x = x
        sum = 0
        for i in range(len(x)):
            sum = sum + self.w[i] * x[i]
        return self.f(sum)

    def backlog(self):
        return self.x

In [67]:
def Test():
    test_neuron = Neuron([2, 3, 4, 5, 6], lambda x: x*x)
    if (test_neuron.forward([1, 2, 3, 4, 5]) == 4900 and test_neuron.backlog() == [1, 2, 3, 4, 5]):
        print("Задание успешно выполнено!")
    else:
        print("Ошибка в решении!")
    
Test()

Задание успешно выполнено!


In [2]:
import numpy as np

In [33]:
a = [1, 2, 3]
b = [2, 3, 2]

def no_numpy_scalar(v1, v2):
    result = 0
    for i in range(len(v1)):
        result += v1[i] * v2[i]
    return result

def numpy_scalar (v1, v2):

    result = np.dot(v1,v2)
    return result

In [34]:
numpy_scalar (a, b)

14

In [35]:
no_numpy_scalar(a, b)

14

In [67]:
a = np.array([
    [1, 2, 1],
    [1, 1, 1],
    [1, 2, 1]
])

def diag_2k(a):
    a = a.diagonal()
    result = 0
    for i in a:
        if(i%2 == 0):
            result += i
    return result
    

In [68]:
diag_2k(a)

0

In [75]:
def cumsum(A):
    #param A: np.array[m,n]
    #YOUR CODE

    result = np.cumsum(A,1)
    return result

In [74]:
cumsum(a)

array([[1, 3, 4],
       [1, 2, 3],
       [1, 3, 4]], dtype=int32)

In [253]:
import numpy as np

X = np.array([
     [1,2,3],
     [1,2,3]
])


def transform(X, a=1):
    B = np.array(X)
    for index, x in np.ndenumerate(B):
        if index[1]%2 == 0:
                B[index] = x**3
        else:
            B[index] = a
    B = np.fliplr(B)
    
    result=np.concatenate((X, B), axis=1)
    return result

In [254]:
transform(X, a=1)

array([[ 1,  2,  3, 27,  1,  1],
       [ 1,  2,  3, 27,  1,  1]])

In [271]:
a = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
import numpy as np
from itertools import groupby

def encode(a):
    return zip(*((key, len(tuple(group))) for key, group in groupby(a)))

In [276]:
import numpy as np

def encode(a):              
        n = len(a)
        if n == 0: 
            return (None, None, None)
        else:
            y = np.array(a[1:] != a[:-1])   
            print("y = {}".format(y))
            print("where(y) = {}".format(np.where(y)))
            i = np.append(np.where(y), n - 1)   
            print("i = {}".format(i))
            z = np.diff(np.append(-1, i)) 
            print("z = {}".format(z))
            return(a[i], z)

In [277]:
a = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
print(encode(a))

y = [ True False  True False  True False  True False  True  True False]
where(y) = (array([0, 2, 4, 6, 8, 9], dtype=int32),)
i = [ 0  2  4  6  8  9 11]
z = [1 2 2 2 2 1 2]
(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))
