In [31]:
import numpy as np

In [6]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [10]:
np.delete(a, [1,7])

array([1, 3, 4, 5, 6, 7, 9])

In [25]:
a = np.eye(4)
a[:, ::-1]

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

Ниже способ унать документацию

In [33]:
?np 