In [1]:
import numpy as np
import pandas as pd

In [6]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [10]:
np.delete(a, [1,7])

array([1, 3, 4, 5, 6, 7, 9])

In [25]:
a = np.eye(4)
a[:, ::-1]

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

Ниже способ унать документацию

In [33]:
?np 

In [40]:
man math

In [27]:
a = np.array([
    [2, 1, 3],
    [1, 2, 3],
    [0, 5, 1]
])
np.array(a.T) #Транспонтрование


array([[2, 1, 0],
       [1, 2, 5],
       [3, 3, 1]])

$P(A \mid B) = \frac{P(B \mid A)P(A)}{P(B)}$

In [15]:
np.linalg.det(a)

-11.999999999999995

In [26]:
np.linalg.inv(a)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
? np.linalg

In [42]:
1 + 1

2

In [2]:
data = pd.read_csv()

TypeError: parser_f() missing 1 required positional argument: 'filepath_or_buffer'